### PR TITLE
Assignment 2 Postman

### PR DESCRIPTION
**Pull request by saivihitha17**

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please add a screenshot of the certificate or the email you have received towards the same.
@saivihitha17

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Also, please move your folder to `Submissions/Assignment 2/` Path and not inside [SRN]-NAME Folder
@saivihitha17

**Comment by saivihitha17** [comment]
Changed

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Pull request merged**
