### PR TITLE
submitted

### PR DESCRIPTION
**Pull request by saivihitha17**

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi
Please refrain from pushing the node_modules folder. Also, please remove redundant files and folders
Please add this submission under `Submissions/ Assignment 2` Folder
[.DS_Store]

@saivihitha17

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please check your submission. 
Check the folder structure. 
Please submit in the given format.
Please remove thew .DS_Store files
@saivihitha17

**Comment by saivihitha17** [comment]
I have changed it , please review

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
image
image


Please remove these files @saivihitha17

**Pull request closed without merging**
