### PR TITLE
assignment1 - Devaki 

### PR DESCRIPTION
**Pull request by Devaki-Prasad2709**

### CODE REVIEW

**Comment by SarthakSKumar** [comment]
Hi. I see that you have also added Files inside the [SRN]-Name Folder. Could you please remove them from that folder and keep the files under your folder only? @Flamingcarz

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please make the necessary changes

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
image

Please take care of the file inside /Assignments Folder

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Comment by Devaki-Prasad2709** [comment]
Sorry, what? Do you want me to do something?

**Pull request merged**
