### PR TITLE
[PES2202300706]-Atharv_Mittal

### PR DESCRIPTION
**Pull request by atharv24mittal**

### CODE REVIEW

**Comment by SarthakSKumar** [comment]
Hi.
Please include a screenshot of the webpage. 
@atharv24mittal

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please make the necessary changes,

**Comment by atharv24mittal** [comment]
WEATHER APP

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Pull request merged**
