### PR TITLE
PES2UG22CS069 Anikethan Rao

### PR DESCRIPTION
**Pull request by Aniikkk**
please merge req

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi
Please remove the .DS_Store file that is added along with this PR
@Aniikkk 

image

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
File still exists in the PR @Aniikkk

**Comment by Aniikkk** [comment]
done

**Review by SarthakSKumar — COMMENTED** [review]
PR is being closed @Aniikkk

**Pull request closed without merging**
