### PR TITLE
changed

### PR DESCRIPTION
**Pull request by samyak2003-coder**

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi.
A few changes before this PR can be merged.
1. I see that this PR is deleting a submission made by another person in the repository. Please make sure this doesn't happen. 
2. You were supposed to use basic HTML, CSS, and Vanilla JS for this Assignment. Please make sure you stick to this tech stack for now.
3. For Node.js based Projects, we don't push the /node_modules folder into the repository since these are packages that developers would install in their local systems during development and pushing these modules into hosted repositories would take up a lot of memory and slower pull/push b/w repositories.

**Comment by samyak2003-coder** [comment]
Noted Sarthak, my apologies for not being aware of these.
Is it possible that the changes can be done after isas?
As ill have remake the project and itll need a few hours

**Comment by SarthakSKumar** [comment]
Hi @samyak2003-coder 
The instructions about the assignment were quite clear, there isn't much I can do for you here. Do submit the assignment at the earliest and will have a look at it.

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
image

There is another assignment that is being deleted in this PR. Please resolve this, you'll be good to go then.
@samyak2003-coder

**Review by SarthakSKumar — COMMENTED** [review]
PR is being closed @samyak2003-coder

**Pull request merged**
