### PR TITLE
Assignment 1 submission.

### PR DESCRIPTION
**Pull request by akshatnavlani**
Note: The frequent cities ferature is just an idea and does not work.

### CODE REVIEW

**Comment by SarthakSKumar** [comment]
Hi. 
Please include a screenshot of the webpage in the same directory. 
@akshatnavlani

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Please make the necessary changes!

**Comment by akshatnavlani** [comment]
Done. Please check now

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Pull request merged**
