### PR TITLE
Assignment by Yash Sharma

### PR DESCRIPTION
**Pull request by Yashs1398**

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi.
Have you tested this locally? I didn't find any scripts in package.json.
@Yashs1398

**Comment by Yashs1398** [comment]
hi @SarthakSKumar  , resubmitting the assignment, can you please check and get back?

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Pull request merged**
