### PR TITLE
Postmann Certificate

### PR DESCRIPTION
**Pull request by Devaki-Prasad2709**
postmann certificate.

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi.
Please Add your submission under `Submissions/Postman Certifcates/`
@Flamingcarz

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi. 
Please refrain from pushing the node_modules folder into the repository

**Comment by Devaki-Prasad2709** [comment]
Okay. Do I remove it?

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Another minor change.
Please move the certificate file out of the [SRN] Folder in `Submissions/Postman Certificates`
@Flamingcarz

**Comment by Devaki-Prasad2709** [comment]
Done.

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Pull request merged**
