### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by RamPrakhyath05**
Used GPT for the code of Multer module

### CODE REVIEW

**Review by SarthakSKumar — CHANGES_REQUESTED** [review]
Hi.
Please refrain from pushing the node_modules folder into the repository.
Please submit a screenshot with a demo output.
Please remove the uploads folder, it seems to be redundant in the context.
@RamPrakhyath05

**Comment by RamPrakhyath05** [comment]
Ok so shall i remove node_modules and Uploads?

**Comment by RamPrakhyath05** [comment]
Is it fine now?

**Review by SarthakSKumar — APPROVED** [review]
Approved!

**Comment by RamPrakhyath05** [comment]
I have reuploaded the assignment with screenshots of the application. Made another pull request with the screenshots

**Pull request merged**
